### ISSUE TITLE
gprbuild: no compiler for language "Ada"

### ISSUE THREAD

**Issue by yrashk** [fluffynukeit/adaspark#3]
Hey, first of all, amazing work, thank you for creating this flake! 👍 🙇 

I am relatively new to Ada so I am wondering if I am missing something. I've used the flake (with `nix shell fluffynukeit/adaspark`) but when trying to use gprbuild I get this error:

```
project.gpr:1:09: no compiler for language "Ada", cannot compile "project.ads"
```

When trying to run 

```
gprconfig --config=Ada --config=C --batch
```

I get this:

```
gprconfig: can't find a native toolchain for language 'Ada'
```

Do you by any chance have an idea what I might be doing wrong? :)

Thanks!

**Comment by yrashk** [comment]
Partial success finding GNAT manually:

```
 gprconfig --config=Ada,,,/nix/store/awm4f3lk7sd1ymqh3w2xk5wz1yv178im-gnat-10.2.0/bin,
```

(my discovery was that gprconfig will be looking for `gnatls` but it is nowhere to be found in `adaspark` derivation)

But this still results in an error:

```
gprbuild: unable to locate archive builder "ar"
```

If `ar` is supplied (by `binutils-unwrapped` or by fixing `ar` in `default.cgpr` to `/nix/store/awm4f3lk7sd1ymqh3w2xk5wz1yv178im-gnat-10.2.0/bin/gcc-ar`), still getting this:

```
Link
   [link]         main.adb
/nix/store/vfqlryhvm8063hs7ax9k2vb8wmch5v0v-binutils-2.31.1/bin/ld: cannot find crt1.o: No such file or directory
/nix/store/vfqlryhvm8063hs7ax9k2vb8wmch5v0v-binutils-2.31.1/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
```

**Comment by fluffynukeit** [comment]
Are you running exactly this command?  The command you put previously is missing some of it.  Notice there is a "github:" part to it.  Also did you enable flakes support on your nix?

`nix shell github:fluffynukeit/adaspark`

Edit: I misread your original comment.  I'm not getting the same error as you are, but I am getting some odd behavior when trying to run gprbuild.  I think the problem is that GPR_PROJECT_PATH environment variable is not being set if you use the command line shell interface, but it is being set if you were to use `adaenv.mkDerivation`.  What is the value of `echo $GPR_PROJECT_PATH` when you are getting these bad shell results?

**Comment by fluffynukeit** [comment]
In addition to my edit comment, you might also see if the `adaenv.mkDerivation` function can be used to build your project as a nix derivation.  I admit my Ada, GNAT, and gprbuild experience is next to 0.  I was able to get this flake set up but haven't used gprbuild for a new project, instead using gnatmake.  You might be finding undiscovered issues.

**Comment by fluffynukeit** [comment]
I've been working to try to integrate GPR_PROJECT_PATH into the shell environment.  It hasn't been going smoothly, partly because `buildEnv` nix function is not documented very well.  My hunch is this is the issue.  The derivation declarations in the flake have no problem finding and building various gprprojects, with no complaints about not finding the compiler.  I think the issue is most likely with the shell environment.  I likely won't be able to make any headway on it until after the weekend, though.

**Comment by yrashk** [comment]
> Are you running exactly this command? The command you put previously is missing some of it. Notice there is a "github:" part to it. Also did you enable flakes support on your nix?
> 
> `nix shell github:fluffynukeit/adaspark`
> 
> Edit: I misread your original comment. I'm not getting the same error as you are, but I am getting some odd behavior when trying to run gprbuild. I think the problem is that GPR_PROJECT_PATH environment variable is not being set if you use the command line shell interface, but it is being set if you were to use `adaenv.mkDerivation`. What is the value of `echo $GPR_PROJECT_PATH` when you are getting these bad shell results?

This is what I get:

```
$ echo $GPR_PROJECT_PATH

```

**Comment by fluffynukeit** [comment]
What gpr project are you trying to build?  I'll try to use it as a debugging case.

**Comment by fluffynukeit** [comment]
Ok, some progress but mostly seems like catching up to you.

I managed to get the GPR_PROJECT_PATH set in the shell but just ran into subsequent issues, so no magic bullet there.  The absence of gnatls looks to be the most likely problem.  Turns out that the nixpkgs version of gnat10 only installs [gnatmake, gnatbind, and gnatlink](https://github.com/NixOS/nixpkgs/blob/91b77fe6942fe999b1efbe906dc98024d1917c0d/pkgs/build-support/cc-wrapper/default.nix#L213), and not the many other gnat* utilities, one of which is gnatls (I presume because it is present next to gnatmake in the gcc source codebase).  I think the nixpkgs derivation for gnat10 needs to be fixed to include these other utilities.  I'll try to get to it this upcoming week.  One risk it that the new derivation might invalidate the binary cache results and require a "rebuild the world" task.

**Comment by yrashk** [comment]
I actually found gnatls in the installed gnat derivation, but it wasn't
wrapped in gnat-wrapper, perhaps that's the reason?

**Comment by fluffynukeit** [comment]
I think so because gnat-wrapper is what goes on the path.  I think it wraps the gnat-10.2.0 binaries, but only some select ones like gnatmake.  I suspect the other binaries need to be wrapped and added to the path *or* just get the `gnat-10.2.0/bin` directory on the path after gnat-wrapper so things like `gnatls` are found but the wrapped `gnatmake` takes precedence over the unwrapped version.  I'm a little surprised that only a handful of gnat utilities get installed when there are about twice as many.

```
ls /nix/store/l9dff390vs1j2fj58aqclw8zrfvxnj2w-gnat-wrapper-10.2.0/bin/
as  c++  cc  cpp  g++  gcc  gnatbind  gnatlink  gnatmake  ld  ld.bfd  ld.gold
```
```
ls /nix/store/0rvxfwhl3sk2n6mg8560r9cifr7yb1wb-gnat-10.2.0/bin
c++         gnat       gnatprep
cpp         gnatbind   gnatxref
g++         gnatchop   lto-dump
gcc         gnatclean  x86_64-unknown-linux-gnu-c++
gcc-ar      gnatfind   x86_64-unknown-linux-gnu-g++
gcc-nm      gnatkr     x86_64-unknown-linux-gnu-gcc
gcc-ranlib  gnatlink   x86_64-unknown-linux-gnu-gcc-10.2.0
gcov        gnatls     x86_64-unknown-linux-gnu-gcc-ar
gcov-dump   gnatmake   x86_64-unknown-linux-gnu-gcc-nm
gcov-tool   gnatname   x86_64-unknown-linux-gnu-gcc-ranlib

```

**Comment by fluffynukeit** [comment]
I started working on updating nixpkgs to include the missing gnat* utilities like gnatls.  Hopefully it works out.

**Comment by yrashk** [comment]
Interestingly enough, when I simply install `gnat10` into my environment, gnatls is available.

**Comment by yrashk** [comment]
Another note -- if `gnat10` is already in the environment, subsequent invocation of `nix shell` for this flake makes gprbuild work out of the box -- but it still can't link due to `crt1` problem.

**Comment by fluffynukeit** [comment]
The adaenv derivation in the flake has a fix for the crt1 problem, I
think.  You might be able to adapt it.

**Comment by fluffynukeit** [comment]
When you say you install it into your environment, do you mean with nix-env installation?

**Comment by yrashk** [comment]
Well, not really, I effectively meant `nix-shell -p gnat10`. Sorry for the confusion!

**Comment by fluffynukeit** [comment]
I've been working on deciphering this and I think I've discovered the root issue.  I'll document it here so I can take a break for today.  gprbuild will invoke gprconfig.  gprconfig searches for installed Ada support.  It does this by finding the location of gnatls.  It then looks for [runtime files](https://github.com/AdaCore/gprconfig_kb/blob/4ee815c3aaf9412785b3d5aeccdf69b8a1958b64/db/compilers.xml#L198) relative to this location.  So there are two complications right now.

1. gnatls is not installed to the gnat-wrapper derivation, so it doesn't end up on the path.
2. If gnatls and other missing gnat* executables are added to the gnat-wrapper derivation (I modified nixpkgs to do this), then gprconfig can find gnatls, but there are no runtime files relative to that location, so it cannot find Ada language support.

The cleanest solution is to ensure that the unwrapped gnat-10.2 derivation/bin gets added to PATH after the gnat-wrapper derivation.  Igprconfig should find gnatls in gnat-10.2 and then find the relative path runtime files.  The wrapped executables will still be found in gnat-wrapper instead.  As a bonus this might require no modifications to nixpkgs, although gnatchop might (still) be broken.

Your doing `nix shell -p gnat10` accomplishes the same thing because the nix user environment ends up near the end of the PATH when running nix shell on the flake.

**Comment by fluffynukeit** [comment]
Whew, ok, like a lot of nix exercises, this required a lot of nix code spelunking to find out what was wrong and find the right card to pull.  Please try out the latest version, which just required adding "gnat10.cc" to the adaspark environment.  Just plain gnat10 is the wrapper version that omits all the files that gprconfig looks for.  If it's still broken then please let me know of a specific gpr project that is failing to build in the nix shell so I can use it to debug the issue further.

**Comment by yrashk** [comment]
gprbuild can now find Ada, but can't find `ar` (I worked around by adding `binutils-unwrapped` to my shell), after that:

```
   [link]         main.adb
/nix/store/vfqlryhvm8063hs7ax9k2vb8wmch5v0v-binutils-2.31.1/bin/ld: cannot find crt1.o: No such file or directory
/nix/store/vfqlryhvm8063hs7ax9k2vb8wmch5v0v-binutils-2.31.1/bin/ld: cannot find crti.o: No such file or directory
```

I am attaching a sample project (to be built with `gprbuild`). It's really just an empty project.

[project.zip](https://github.com/fluffynukeit/adaspark/files/6276266/project.zip)

**Comment by fluffynukeit** [comment]
Ok, I can compile your example project using the latest version.  I had to change to `nix develop` instead of `nix shell` to start the environment.  It's kind of a nix code smell to me, but it works.  I really would love for the buildEnv function to support shellHook or generally for nix shell to allow setting env variables instead of just installing packages.  To do it the "right" way I think I would have to make at least one wrapper executable for the linker to set the LIBRARY_PATH before invocation.  I might still do that as a cleanup exercise.

**Comment by yrashk** [comment]
Woohoo! 🎆  Works on my end, too! Thank you so much! 🙇
